name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'starling-v*-release'
      - 'v*-release'
    tags:
      - 'v*'
      - 'starling-v*'

jobs:

  c:
    strategy:
      matrix:
        include:
          - {os: ubuntu-18.04, cc: "gcc-6", cxx: "g++-6", test_suite: "unit"}
          - {os: ubuntu-18.04, cc: "clang-6.0", cxx: "clang++-6.0", test_suite: "lint"}
          - {os: macos-10.15, cc: "clang", cxx: "clang++", test_suite: "unit"}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Install gcc-6
        if: matrix.os == 'ubuntu-18.04'
        run: |
          sudo apt-get update && \
          sudo apt-get install build-essential software-properties-common -y && \
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
          sudo apt-get update && \
          sudo apt-get install -y \
            clang-6.0 clang-format-6.0 clang-tidy-6.0 \
            libc++-dev libc++abi-dev \
            gcc-6 g++-6
      - name: Run build
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
          TEST_SUITE: ${{ matrix.test_suite }}
        run: |
          bash ./ci-build.sh

  windows-vs-2019:
    name: Windows VS 2019
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Configure
        run: cmake -G "Visual Studio 16 2019" -S c -B build
      - name: Build
        run: cmake --build build --target ALL_BUILD
      - name: Test
        run: cmake --build build --target do-all-tests